package com.geo.constants;

public interface Constants {

	String GOOGLE_GEO_SERVICE_URL = "https://maps.googleapis.com/maps/api/geocode/" ;
	
	/*
	 * Google Geo Address API Key generated by Google
	 * I have modified it due to security reason please generate your own Google Geo Address Service Key 
	 */
	String GOGGLE_GEO_SERVICE_KEY_FOR_RINKU_VATS = "ZIzaSyBaLmPxjNybHkCyvMqyJa_qwTT6DfsRZ2g" ;
}
